package spire.blas;

import java.nio.Buffer;
import com.sun.jna.Native;

public class BlasLib {
  static {
    Native.register("blas");
  }

  /*
  public static native void caxpy_();
  public static native void ccopy_();
  public static native void cdotc_();
  public static native void cdotu_();
  public static native void cgbmv_();
  public static native void cgemm_();
  public static native void cgemv_();
  public static native void cgerc_();
  public static native void cgeru_();
  public static native void chbmv_();
  public static native void chemm_();
  public static native void chemv_();
  public static native void cher_();
  public static native void cher2_();
  public static native void cher2k_();
  public static native void cherk_();
  public static native void chpmv_();
  public static native void chpr_();
  public static native void chpr2_();
  public static native void crotg_();
  public static native void cscal_();
  public static native void csrot_();
  public static native void csscal_();
  public static native void cswap_();
  public static native void csymm_();
  public static native void csyr2k_();
  public static native void csyrk_();
  public static native void ctbmv_();
  public static native void ctbsv_();
  public static native void ctpmv_();
  public static native void ctpsv_();
  public static native void ctrmm_();
  public static native void ctrmv_();
  public static native void ctrsm_();
  public static native void ctrsv_();
  public static native void dasum_();
  */
  public static native void daxpy_(int n, double da, Buffer dx, int incx, Buffer dy, int incy);
  /*
  public static native void dcabs1_();
  public static native void dcopy_();
  public static native void ddot_();
  public static native void dgbmv_();
  public static native void dgemm_();
  public static native void dgemv_();
  public static native void dger_();
  public static native void dnrm2_();
  public static native void drot_();
  public static native void drotg_();
  public static native void drotm_();
  public static native void drotmg_();
  public static native void dsbmv_();
  */
  public static native void dscal_(int n, double da, Buffer dx, int incx);
  /*
  public static native void dsdot_();
  public static native void dspmv_();
  public static native void dspr_();
  public static native void dspr2_();
  public static native void dswap_();
  public static native void dsymm_();
  public static native void dsymv_();
  public static native void dsyr_();
  public static native void dsyr2_();
  public static native void dsyr2k_();
  public static native void dsyrk_();
  public static native void dtbmv_();
  public static native void dtbsv_();
  public static native void dtpmv_();
  public static native void dtpsv_();
  public static native void dtrmm_();
  public static native void dtrmv_();
  public static native void dtrsm_();
  public static native void dtrsv_();
  public static native void dzasum_();
  public static native void dznrm2_();
  public static native void _fini();
  public static native void icamax_();
  public static native void idamax_();
  public static native void _init();
  public static native void isamax_();
  public static native void izamax_();
  public static native void lsame_();
  public static native void sasum_();
  public static native void saxpy_();
  public static native void scabs1_();
  public static native void scasum_();
  public static native void scnrm2_();
  public static native void scopy_();
  public static native void sdot_();
  public static native void sdsdot_();
  public static native void sgbmv_();
  public static native void sgemm_();
  public static native void sgemv_();
  public static native void sger_();
  public static native void snrm2_();
  public static native void srot_();
  public static native void srotg_();
  public static native void srotm_();
  public static native void srotmg_();
  public static native void ssbmv_();
  public static native void sscal_();
  public static native void sspmv_();
  public static native void sspr_();
  public static native void sspr2_();
  public static native void sswap_();
  public static native void ssymm_();
  public static native void ssymv_();
  public static native void ssyr_();
  public static native void ssyr2_();
  public static native void ssyr2k_();
  public static native void ssyrk_();
  public static native void stbmv_();
  public static native void stbsv_();
  public static native void stpmv_();
  public static native void stpsv_();
  public static native void strmm_();
  public static native void strmv_();
  public static native void strsm_();
  public static native void strsv_();
  public static native void xerbla_();
  public static native void zaxpy_();
  public static native void zcopy_();
  public static native void zdotc_();
  public static native void zdotu_();
  public static native void zdrot_();
  public static native void zdscal_();
  public static native void zgbmv_();
  public static native void zgemm_();
  public static native void zgemv_();
  public static native void zgerc_();
  public static native void zgeru_();
  public static native void zhbmv_();
  public static native void zhemm_();
  public static native void zhemv_();
  public static native void zher_();
  public static native void zher2_();
  public static native void zher2k_();
  public static native void zherk_();
  public static native void zhpmv_();
  public static native void zhpr_();
  public static native void zhpr2_();
  public static native void zrotg_();
  public static native void zscal_();
  public static native void zswap_();
  public static native void zsymm_();
  public static native void zsyr2k_();
  public static native void zsyrk_();
  public static native void ztbmv_();
  public static native void ztbsv_();
  public static native void ztpmv_();
  public static native void ztpsv_();
  public static native void ztrmm_();
  public static native void ztrmv_();
  public static native void ztrsm_();
  public static native void ztrsv_();
  */
}
